---

- debug:
    var: "{{ item }}"
  with_items:
    - aws_asg_input
    - _aws_lc
    - _aws_asg
    - _aws_sg_for_lb
    - _aws_lb
    - _aws_tags_dict
    - _aws_tags

- import_tasks: create-load-balancer.yml
- import_tasks: create-launch-configuration.yml
- import_tasks: create-auto-scaling-group.yml
- import_tasks: wait-for-lb-to-be-healthy.yml
- import_tasks: update-dns.yml
- import_tasks: cleanup/main.yml
